theme: jekyll-theme-minimal
title: CS209 Data Structures and Mathematical Foundations
# For local development, use:
#url: "http://localhost:4000"
#baseurl: ""
# For GitHub Pages later, change to:
url: "https://kcandon-skidmore.github.io"
baseurl: "/cs209-fall26"